### ISSUE TITLE
Server crash (Unhandled Exception)

### ISSUE THREAD

**Issue by ratozumbi** [JackD83/ALVR#221] opened 2020-06-23 09:05 UTC
I was having [this ](https://github.com/polygraphene/ALVR/issues/506) issue and I tried to fix it by upgrading my nvidia driver (I was using version 417.71 as suggested by  @AndreyLebedenko, but it was not working) now I am using version 446.14 and the error shown by ALV has changed to

```Unhandled Exception.
ExceptionCode=C0000005
Address=00007FFA6762C344 (00007FFAA52A0000 + FFFFFFFFC238C344)
```
Steam VR window opens but shows error 301

To replicate this error the option "Launch only steam vr without steam" must be checked on the Other tab. If it's not checked, Steam VR window open and closes right afterwards and no error message is presented by ALVR or steam.

My system:
 i7-6700HQ CPU @ 2.60GHz
Intel(R) 100 Series/C230 Series Chipset
NVIDIA GeForce GTX 960M
Intel(R) HD Graphics 530
vc_redist.x64.exe installed

I know the obvious solution is that ALVR is conflicting with the integrated intel graphics, but I don't know how to disable that card to only use the gtx 960m
I know I can force nvidia to be used on a specific configured program using nvidia panel, but ALVR is not showing up on the list to be added. Anyway, the global configuration is set to use the gtx 960m

**Comment by JackD83** [comment] 2020-06-23 09:20
Duplicate of #188 
The 960M is now 5 years old and probably below minimum requirements for most of the VR games.
In addition, I think that it does not support h265, so you could try to lower the video resolution to 50% and chose h264.

**Closed by JackD83** 2020-06-23 09:20 UTC
