### ISSUE TITLE
Compile error!

### ISSUE THREAD

**Issue by brianchung0803** [JackD83/ALVR#302] opened 2020-09-02 09:13 UTC
# Please follow the general troubleshooting steps first:

- [done] I carefully followed the instructions in the [README](https://github.com/JackD83/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [ done] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

Dear JackD83,
  I have been using your work "ALVR" for a long time, and I really admire it. However, there's an error that occurred when I tried to compile the project using command line: cargo xtask build-server --release. 
  The attached image is the screenshot of the problem. Thanks.  
  P.S. I compiled it successfully for the past 2 months, the issue happened 2 days ago.

![螢幕擷取畫面 (118)](https://user-images.githubusercontent.com/52735509/91962550-3ff58900-ed3f-11ea-8d28-8a0ccf041d72.png)

**Comment by zarik5** [comment] 2020-09-02 11:00
This is caused by a library that made breaking changes without respecting the semver rules. Waiting for #299.

**Comment by maxer456** [comment] 2020-09-02 20:12
The issue is that the `fs_extra` crate changed a signature of one of its functions to a more generic one (using a slice instead of a `Vec`). This made Rust unable to infer the correct type of a variable. #299 includes a fix for that, so I'm closing the issue.

**Closed by maxer456** 2020-09-02 20:12 UTC
