### ISSUE TITLE
Any chance to support Steam VR Input?

### ISSUE THREAD

**Issue by jbpauljr** [JackD83/ALVR#26] opened 2019-09-07 00:33 UTC
I was trying out Vivecraft with your experimental version 5 (which is excellent, by the way) and the controllers didn't work at all. After googling, I found out that ALVR doesn't currently support the SteamVR input system that the current versions of vivecraft use. For your reference: http://www.vivecraft.org/vivecraft-steamvr-input/

If you could add that to the build I'd really appreciate it! Thanks for your great work.

**Comment by JackD83** [comment] 2019-09-09 07:02
I'm not sure what to make of this issue. The controller are registered as Oculus Touch controller in Steam VR and every thing, including rebinding of buttons is working fine. 

I tried the free Aircar tech-demo on steam which also requires setting up you controls using SteamVR input. This worked very well by just loading a community preset.

[Aircar Setup](https://steamcommunity.com/sharedfiles/filedetails/?id=1830980067&insideModal=0)

Have you tried to map your configuration for vivecraft or load a configuration?

 I don't own minecraft, so I can not checkt.

**Comment by jrbudda** [comment] 2019-09-29 03:03
Vivecraft is looking for interface IVRInput_006. I do not know how to check what version the alvr server is supporting.

**Comment by JackD83** [comment] 2019-09-29 07:10
ALVR is implementing a openvr driver following the openvr sample driver from [here](https://github.com/ValveSoftware/openvr/tree/master/samples/driver_sample)

There is no reference of a IVRInput in it. I'm not sure if the IVRInput interface is something the clients implement.

Googeling your IVRInput_006, I found a bug entry on [proton](https://github.com/ValveSoftware/Proton/issues/2884) that Tilt Brush is not working with a missing  IVRInput_006 error. 
I checked Tilt Brush this morning and its also working flawless with ALVR

**Comment by Avencore** [comment] 2019-10-05 20:58
Vivecraft version 1.12.2 is the last one that works with alvr currently, if anyone is interested.

**Comment by KitsuneShan** [comment] 2019-10-06 00:08
@Avencore the controller layout it's extremely confusing in this way tho.
Commenting mostly in case that a fix it's done on this. Some people reported that on Virtual Desktop it works fine. I have no Virtual Desktop so I can't opine on that. All I can say it's that ALVR works perfectly fine on every single game except Vivecraft. So do not know either if a manual fix has been added to Virtual Desktop as a workaround. What it is the issue, which seems to be on Vivecraft side, I hope it gets sorted soon as I would like to play. But not on legacy controllers that are pretty weird, I couldn't even rotate with any of the sticks and to walk forward I had to push trigger. And yeah I know I can customize them but I'll pass, I hate editing legacy controllers.
Following the progress on this. Thanks to both party for your hard wor! ♥

**Comment by Avencore** [comment] 2019-10-06 11:38
@JackD83 Any chance you could try updating the bundled openvr driver? Would try to help you but im not that well versed in C.

**Comment by KitsuneShan** [comment] 2019-10-06 17:49
@JackD83 I am not sure about opening a new issue or commenting here because it may be related.
Today, SteamVR Beta was updated to 1.8.9 when I opened it. Yeah, I was on the beta because I had issues before and going to the Beta these problesm disappeared so I didn't care about going back, all was working fine after all. The thing is that with 1.8.9, the system button from left controller doesn't seemed to work so I couldn't launch SteamVR interface to launch games. This never happened before and if I open the games just on computers they load fine, I just keep there on the empty space without any Steam menu if I press that button. So I guess it somewhat works but not completely. I guess it can be just a simple casual issue but nothing fixed it except going back to no beta version. Chances are that such "issue" may be fixed before going out of the beta channel. I am just aknowledging it here because maybe it could have something to do with how Vivecraft doesn't detects the controls properly, as if Steam may update something and make ALVR to not work right anymore untill updated. So I just tell in advance in case that some measures could be necessary. Hopefully this may be just a casual bug or something that wont happen on the release channel but I guess it's worth mentioning just in case that someone runs into the same issue

**Comment by JackD83** [comment] 2019-10-07 12:04
@Avencore there is no bundled openvr driver, the driver that comes with alvr is the main component of alvr and contains all the magic. ALVR is not using any kind of legacy input and SteamVR input is well supported in any other app besides vivecraft.

@KitsuneShan I tried the beta and had the same issue as you. The button works fine and SteamVR is reacting to it, but not showing the overlay. Just wait for another update, I'm sure they will fix this.

**Comment by Avencore** [comment] 2019-10-07 12:45
@JackD83 Okay I get it. Seems I confused the driver part with what other applications need to implement. I tried to remap the controls in Steam but no possible combination seemed to work. Controllers are just stuck in front of the HMD.
If you are willing to inspect this issue further I would gift you Minecraft so you could try to find a workaround.

**Comment by JackD83** [comment] 2019-10-07 13:44
I would accept any gifted game, at leased I can look into it. But I cannot make any promises!
I would guess that a few people are interested in Minecraft working wireless on the quest until there is a mobile version

**Comment by KitsuneShan** [comment] 2019-10-07 15:03
@JackD83 there is the GearVR version that can be sideloaded but we can't compare the version of Vivecraft with the mobile version. Isn't just because mobile oen looks worse and way more simple, it's because the mobile version it's extremely simple. Basically it's like the Windows 10 version, console Minecraft with VR camera while Vivecraft let you use your own hands to play. I still feel like the problems on the controllers are more on Vivecraft side since ALVR works just on every single game I tried. But I am not programmer, I just guess that if Steam detects the controllers as touch controllers and every single game works just fine, I don't see why this one shouldn't.

I spent some time with the devs and sent them logs and stuff. I am not sure if any of that would be helpful for you but we could see that Vivecraft was just not identifying the headset or controllers, basically it was giving error detecting VR even tho it did display in VR just fine.

**Comment by jrbudda** [comment] 2019-10-07 17:13
Our problem is that the VRInput interface fails to load. We load several
openVR interfaces: system, compositor, rendermodels, settings, application,
and input. With alvr (and riftcat), only the system and compositor
interfaces load. The rest fail with unknown error (3) and that's all I
know. Maybe steamvr logs would provide more information but I have not
tried myself.

**Comment by KitsuneShan** [comment] 2019-10-07 18:52
Hope you guys could work a little together to get it sorted. It definitely would be something great for all us that uses ALVR. All I can do it's help on whatever you guys need. If you guys need logs, test this or that, etc... I can lend a hand.

**Comment by JackD83** [comment] 2019-10-19 09:17
@Avencore was so kind and gifted me a copy of Minecraft and I made some initial testes.
As expected, Vivecraft was not loading for me as well and the VR process was only listed as javaw.exe (the jvm)

After changing the names of the emulated driver, Vivecraft is properly loaded and the SteamVR bindings can be changed. Problem is that the input is still not working and the controllers are not even tracked.

Does someone own a  Rift-S that is working with Vivecraft and can tell me the following parameters:

HMD
- driverConfig.serialNumber = "WMHD000X000XXX";
- driverConfig.trackingSystemName = "oculus";
- driverConfig.modelNumber = "Oculus Rift S";
- driverConfig.manufacturerName = "Oculus";
- driverConfig.renderModelName = "generic_hmd";
- driverConfig.registeredDeviceType = "oculus_rifts";

Controller:
- driverConfig.controllerTrackingSystemName = "oculus";
- driverConfig.controllerManufacturerName = "Oculus";
- driverConfig.controllerModelNumber = "Oculus Rift S";
- driverConfig.controllerRenderModelNameLeft = "oculus_rifts_controller_left";
- driverConfig.controllerRenderModelNameRight = "oculus_rifts_controller_right";
- driverConfig.controllerSerialNumber = "WMHD000X000XXX_Controller";
- driverConfig.controllerType = "oculus_touch";
- driverConfig.controllerRegisteredDeviceType = "oculus_touch";
- driverConfig.controllerLegacyInputProfile = "oculus_touch";
- driverConfig.controllerInputProfilePath = "{oculus}/input/touch_profile.json";

These are the settings that I used to make it show up, maybe its just a matter of the right names.
I don't know how to get them, but I think they are somehow exposed trough openVR

On the other hand, its a little problematic to rely on the name of the HMD in the first place. New HMDs could always use something else

**Comment by jrbudda** [comment] 2019-10-19 14:27
Thanks for looking into this @JackD83. I don't have a rift s but I will ask in our discord for some users to help. Also if you can grab and upload your .minecraft/logs/latest.log file I can look at it and see if the errors have changed to provide some more insight.

**Comment by jrbudda** [comment] 2019-10-19 14:36
Also just wanna throw this out there, if you start up Vivecraft and the VRInput interface fails to load, it forces the game into seated (keyboard/mouse) mode, which persists via a setting.

If, when you get to the main menu, your controllers are kinda in front of you at chest height, check in the vroptions menu to make sure seated mode isn't on. I'd hate for you to waste time trying to fix what you've already fixed due to a setting :)

**Comment by JackD83** [comment] 2019-10-19 17:19
> I'd hate for you to waste time trying to fix what you've already fixed due to a setting :)


Too late :P
You can find a test version [here](https://drive.google.com/open?id=14jQuBjpq-uU44WjHSzpIRK2EpToVvGFr)

Vivecraft works for me, but I dont't know if it breaks anything. Please test and report back. You need the ev7

I still think relying on the manufacturer name being HTC,Oculus or WindowsMR is a fault of the client.

**Comment by KitsuneShan** [comment] 2019-10-19 18:00
Tested Vivecraft, I can confirm that works like a charm. Need to test some other games but I don't see why others shouldn't work. Thanks a lot :smile:

**Comment by eyelykaynal** [comment] 2019-10-25 17:16
> Does someone own a Rift-S that is working with Vivecraft and can tell me the following parameters:

Here's the info from an actual Rift S:

HMD
TackingSystem: "oculus".
SerialNumber: "1WMGH000XX0000".
ModelNumber: "Oculus Rift S".
ManufacturerName: "Oculus".
RenderModelName: "generic_hmd".
RegisteredDeviceType: "oculus/1WMGH000XX0000".
DriverVersion: "1.42.0".

LCTRL
TackingSystem: "oculus".
SerialNumber: "1WMGH000XX0000_Controller_Left".
ModelNumber: "Oculus Rift S (Left Controller)".
ManufacturerName: "Oculus".
RenderModelName: "oculus_rifts_controller_left".
RegisteredDeviceType: "oculus/1WMGH000XX0000_Controller_Left".
InputProfile: "{oculus}/input/touch_profile.json".
ControllerType: "oculus_touch".

RCTRL
TackingSystem: "oculus".
SerialNumber: "1WMGH000XX0000_Controller_Right".
ModelNumber: "Oculus Rift S (Right Controller)".
ManufacturerName: "Oculus".
RenderModelName: "oculus_rifts_controller_right".
RegisteredDeviceType: "oculus/1WMGH000XX0000_Controller_Right".
InputProfile: "{oculus}/input/touch_profile.json".
ControllerType: "oculus_touch".

**Comment by JackD83** [comment] 2019-10-25 19:34
Thank you very much! I will updaten ALVR shortly. Wondering if #31 will also be fixed by this

**Comment by eyelykaynal** [comment] 2019-10-26 07:53
No problem.

I thought so too so I changed the existing variables, added "Prop_DriverVersion_String" and rebuilt ALVR. My settings are now read identical to what I posted above, but DCS still has the exact same problem (no VR at all with TrackingSystem "oculus" - which is extremely odd since that's the same as the Rift S which works - and a distorted view when not looking straight ahead with TrackingSystem "Oculus").

Anyway, I just keep a copy of Alpha4 on my computer and run that when I want to play DCS. Little annoying uninstalling/reinstalling the driver all the time but never mind. I don't need the controllers in DCS so it works fine.

I would commit the changes I've made to save you the hassle but I've had to remove all of the AMF stuff to get it to build for some reason.

**Comment by Hubbit200** [comment] 2019-11-11 15:55
@JackD83 Thank you for your amazing work on ALVR!!
I just wanted to ask, how is the update fixing Vivecraft going? Might it be out in the next week or so? Otherwise, does the experimental version you posted above work fine?
Thanks so much, and keep up the great work on this!

**Comment by KitsuneShan** [comment] 2019-11-11 15:59
@Hubbit200 the version posted above works perfectly fine with Vivecraft. I tested it myself and have no issues :smiley_cat: .

**Comment by Hubbit200** [comment] 2019-11-11 16:05
@KitsuneShan Thanks! Do you know if it works fine with SteamVR as well?

**Comment by KitsuneShan** [comment] 2019-11-11 16:17
@Hubbit200 oh yeah. Vivecraft needs SteamVR after all. But if you aren't completely sure, you can have both executables on the same folder which is what I did just in case. The client apk it's the same after all. So if you find any game that doesn't works with the Vivecraft version, just launch the server with the other one.

**Comment by Hubbit200** [comment] 2019-11-11 16:48
Ok, thanks!

**Comment by JackD83** [comment] 2019-11-26 10:16
Fix is included in ev8

**Closed by JackD83** 2019-11-26 10:16 UTC
