### ISSUE TITLE
Jerky head tracking with "0" every few secs

### ISSUE THREAD

**Issue by orangpelupa** [JackD83/ALVR#87] opened 2019-12-05 10:14 UTC
when i set trackingframeoffset to -1, it looks even worse.

the "jerk" looks like "image doubling"

example, easiest to see on contrast line. A line like this (many lines in steam VR default screen without Home launched)

|

at random time, usually every few secs, will look like this when i move my head around

||

I only experience this with 
GTX 1660 Super + i5 4460

it was smooth sailing on
RX580 + Ryzen 7 1700

**Comment by orangpelupa** [comment] 2019-12-06 04:15
I think this is NVENC's issue on TURING

googling around, https://www.google.com/search?q=nvenc+stutter
since 2019 some people complains about stuttering in NVENC

i tried OBS Studio to record UFOTEST https://www.testufo.com/ghosting#background=004040&separation=160&pps=240&graphics=bbufo.png&pursuit=1

The results are:
NVENC = stutter
X264 CPU = smooth

Dang, i should have bough Radeon Vega instead of GTX 1660 SUPER

**Comment by coroiu** [comment] 2019-12-06 22:45
Could this be the stuttering you are seeing?

https://youtu.be/oYs5O1-_DxM

**Comment by JackD83** [comment] 2019-12-07 08:31
I'm pretty sure you are dropping frames in SteamVR. Please open the SteamVR menu and select Developer -> Advanced Frame Timings.

You should not have any spikes above the idle block.

@orangpelupa 
The  i5 4460 is below the minimum spec for VR. Same goes for #83. Your PC is struggling with VR and ALVR is on top of that. ALVR needs a high-end PC and has even higher system requirements as a Rift-S!

@coroiu 
If you can see this stuttering on the PC it can only be two things: Rendering problems as stated above or the tracking packages don't reach ALVR on the PC. My guess would also be the rendering.

**Comment by orangpelupa** [comment] 2019-12-07 09:17
@coroiu yep! It's like that. Controllers didn't stutter but when moving head around, stutters like that

@JackD83 sorry I already packed my quest to be sold so I can't give the frame timing screenshot

When I watch the frame time while in steam vr floating world (not home) there were no spikes and the head stacking stutters. 

when I tried LA moire VR I do get lots of spikes and there are two stutters.

1. Stutters of head and hand (this shows spike on stream vr timing) 
2. Only head stutter (didnt show spikes)

**Comment by coroiu** [comment] 2019-12-07 09:19
My PC is not dropping frames at least, I'm not so sure that it has to do with rendering. I couldn't record the Advanced Frame Timings but I used OpenVR Advanced Settings to show another version. The problem is not as pronounced in the following videos, but it is still clearly there. I'm also uploading a slow-mo version of it where it's easier to see what is actually happening. It looks like the tracking is jumping back to where it was a few frames ago, but hard to say.

Whole video: https://youtu.be/zkBM6a2uzFE 
Slow mo: https://youtu.be/jMsOjPtymqI 

Oh and I'm running on an i7-6700 + GTX 970 (RTX 2070 is in the mail, can probably test next week)

**Comment by orangpelupa** [comment] 2019-12-07 09:50
When I tested a few days ago, My frame timing were smoother than yours and under 2ms. And it still stutter.

I was seeing the frame timing while in the steam vr floating home menu (the one with grids on the floor and aurora as the sky), not the steam home. So there were practically nothing heavy to render.

**Comment by JackD83** [comment] 2019-12-07 09:57
Are you close to a window? I get this tracking back jumps when I'm close to and facing a window. Sunlight has also something to do with it. GTX 970 is also the minimum for VR

> I'm not so sure that it has to do with rendering.

If missing frames, the tracking can not be updated and reprojection kicks in to compensate for your head movement but not for the controller. Tracking information is a very small package that is not altered and fed into SteamVR

Please test one other thing: Create a folder called "logs" inside the ALVR folder next to the ALVR.exe
In the ALVR debug settings, enable the "debugCaptureOutput" checkbox. This will create a very large video file of the output send to the HMD. You can watch the file using FFPlay. See if there are the same problems visible

**Comment by coroiu** [comment] 2019-12-07 11:11
I wouldn't say close (to a window), but that would mean having the same issue outside of ALVR as well, which I am not (no stuttering in Oculus Home on the Quest). 

The controllers are just the most convenient way of showing the problem. The issue is present even without them (moving your head while looking at an object in-game, the whole world just kind of stutters back and forth).

I did the test and the stutter is present in the dumped video file as well.

I tried to test the issue with VRidge, but damn ALVR works better. It's completely unplayable :(
So I tried Oculus Link instead (wow, the low latency is impressive) and there was no stutter whatsoever. So my PC hardware can definitely keep up. I even tried lowering ALVR to 50% resolution, just to make the comparison fair - no dice.

I am seeing some packet loss however, but it's very weird, it seems to only occur when I'm moving the actual headset. It's not much though, jumps to 8 packets/s and then down to 0 again. Keeping the headset still shows almost no packet loss at all. I have line of sight to an AC-66U 3 meters away.

**Comment by orangpelupa** [comment] 2019-12-07 14:13
Hmm maybe these are a different issues? 

in my case, there were zero packet loss.

Only when the headset moves the stutter occurs, of it stays still, no stutter (the controller moved around just fine)

**Comment by coroiu** [comment] 2019-12-07 17:57
Just installed my 2070, same problem

**Comment by clementkirton** [comment] 2019-12-08 00:33
been having the same problem I have 866mbs connect with wifi right next to the router pc is plugged in 1080ti ryzen 1700x and I get like 1 or 2 dropped frames every few seconds no matter what the settings are set to.

**Comment by JackD83** [comment] 2019-12-08 09:01
I agree with @orangpelupa, I think we have now 3 different issues. 

@coroiu I checked your videos again and I'm not sure what I' seeing. Do you get the jumps on view of the HMD or only on the controller? The jumps on the controller have to be considered "normal". In the case of the video, you are moving your tracking reference (the headset) and the controllers. Together with the delay of ~50-70ms, the position of the controller in some frames are only a guess.  Moving the tracking reference makes it some times a bad guess that gets corrected once the next position arrives. 
You can check this if you go to the other tab of alvr and set the pose offset to 0.1 or higher. Then you will have no jumping but very slow moving controllers.

@ all
Network transmission is a very fundamental part of ALVR. Every hiccup, imperfection etc. gets a response in the streaming and we humans are very perceptible to those errors. Your network has to be flawless! With all the errors I have seen from may people, I doubt that Oculus will release a wireless link version that does not come with dedicated hardware for the PC that they can control. 

For your own network, check the following:
- 5gzh Wifi, use a separate ssid for the 5hz and 2,4ghz part. The Quest tends to jump frequencies
- PC has to be wired to the router/AP
- Check if you have the only AP on the 5ghz channel. If not, it won't be perfect. Nothing you can do
- Limit the channel with to 40mhz, 80mhz is causing problems

If you cannot meet all these criteria, you will get problems! If you still have problems, try a different AP just for the quest. 

Some more things are listed [here](https://github.com/JackD83/ALVR/wiki/Setup-advice)

**Comment by orangpelupa** [comment] 2019-12-08 11:24
For those with windows 10, use USB 5GHz wifi.

1. Turn on wifi Hotspot on an android phone, and set it to 5ghz
2. Connect computer wifi to phone
3. Turn on windows 10 Hotspot
4. Disconnect computer wifi from phone Hotspot (keep the computer Hotspot active) and turn off phone Hotspot 

This will give you the lowest possible latency, and cleanest connection. Direct wifi connection to quest at 5ghz.

You need to do those hoops with Android phone Hotspot because windows 10 Hotspot not always have 5ghz option and even if you get that option, the 5ghz sometimes broken (everything looks fine but quest cant see it or can't get ip address, etc)

**Comment by coroiu** [comment] 2019-12-08 21:10
Ok, so maybe they are different issues. Let's forget about the Controller/Head jumping and just focus on the head jitters. Here's a test where I am simply moving my head (clip is slowed down in the middle), and I have to admit that the video from the quest looks like packet loss. I just think it's odd that moving my hands doesn't trigger anything like that.

Clip: https://youtu.be/Wy9iGEb6ndw (ex: 0:14-0:15)

I also dumped the ALVR capture during the same session. This is probably the most interesting part, but if you say that this is related to the packet loss then i give up :). Anyway, the capture just kind of jumps exactly when the Quest shows video artifacts. So I'm guessing this has to be due to tracking information being lost, or something happening in the driver. What do you think? Is this how packet loss manifests?

Clip: https://youtu.be/lWSFQK7fC6Y (ex: 0:07-0:08)

**Comment by JackD83** [comment] 2019-12-09 07:49
Very good videos! Seeing them we can rule out any tracking issues :) The tracking does influence the content of the video e.g. the movement, the video feed itself is not affected by it. Even if you disable the head tracking completely, you would get a nice but disorienting video feed. 

The video player on the PC seems to be capable of handling more errors than on the quest. That's why you see only a small hiccup on the PC and a larger error on the quest. In your other video, the quest did handle it better.

As the error is also present in the encoded video, network seems also not the issue.

That leaves two possibilities I can think of: 
- There is some kind of encoding error while encoding the frame of the game. 
- There is a lag/disruption/stutter in the pipeline Game -> SteamVR -> Encoder 


What you could try: Fresh windows installation, all drivers, no geforce experience, latest SteamVR and try again. That is the only advice I have left.

**Comment by orangpelupa** [comment] 2019-12-09 12:07
Btw try recording UFO TEST on chrome via OBS Studio nvenc or GeForce experience video recording function.

If the ufo stutters, you are affected by NVENC bug that has been there since the launch of turing RTX series. Just like me.

**Comment by coroiu** [comment] 2019-12-10 07:50
Recording my desktop with Nvidia experience resulted in surprisingly no stutter. So maybe you have multiple issues @orangpelupa , or we don't have the same issue. I've also tried searching for "SteamVR stutter" but nothing has worked. However, as it turns out, SteamVR doesn't actually stutter, the stutter is only present in the ALVR dump (and the quest). I plan on doing the same test as above and also checking the log to see if there could be anything in there. Otherwise I don't know, I don't think I will be doing a clean install, to much work and I don't really think it will solve the problem (I appreciate the advice though :smile: ).

**Comment by coroiu** [comment] 2019-12-10 10:06
I'm starting to wonder if this might be related to encoding stutter in NVENC after all. This seems very familiar https://www.youtube.com/watch?v=8YaVkrwalmw . Apparently the fix they've applied in OBS is related to GPU priorities. After some digging I found the commit with the fix: https://github.com/obsproject/obs-studio/commit/ec769ef008b748f7dfba211daec9eb203ea4bea0 .

What do you think @JackD83 ?

**Comment by coroiu** [comment] 2019-12-12 19:41
After much trial and error, I think I might have managed to hack the fix into ALVR. It's not pretty, but it compiles. And... I think it might have fixed it, seems like no more stutter in the encoding dump at least, I'll try to play for a longer period and see. I'll fork and upload tomorrow, but here's the compiled version of the driver if anyone wants to try https://drive.google.com/open?id=1Rkp-Nypq4gfN1pCB7UWUHPgo6yW-Tc-k

You'll have to run SteamVR as administrator, which I think means that you have to run steam in compatibility mode (right click -> properties -> compat -> run as admin). The log should say if the fix fails or succeeds.

**Comment by clementkirton** [comment] 2019-12-13 05:25
IDK I have tried everything now and still getting frame drops and i did not get them like 2 weeks ago.
I have an 866mbit connection 40hz and I'm the only one on the 5ghz channel my PC is not the problem even if I set it to 25% res I still get 0 - 1 frame drops every few seconds. I get this even in a blank steam world it's not performance-related. even with the driver still does it no idea what left to try.

**Comment by coroiu** [comment] 2019-12-13 06:14
Did something change during those two weeks? Windows update? Hardware?

Did the fix in the driver run successfully? Have you checked the log?

I'm also still getting stutter, but a lot less. I'll try to do a more thorough check of the endoded video to see if there really is no stuttering left. However, running at 25mbps (100% Res, HEVC) and activating aggressive keyframe sending seems to help.

**Comment by clementkirton** [comment] 2019-12-13 06:55
will give it a try tomorrow and let you know and yeah I even uninstalled all the driver and only added the one and added the one you had.

**Comment by JackD83** [comment] 2019-12-20 10:54
@coroiu Did you have time to test your fix? I could include it in a next version. The only thing that troubles be is the admin privileges. You should not run games with it

**Comment by clementkirton** [comment] 2019-12-20 14:39
For me he's update did nog help much. It much be that something changed maybe someone new moved in with alot of wifi stuff or something. I'll try it again at some point when I have time do a clean install of Everthing and able to test with less wifi in the area. Thank you

**Comment by clementkirton** [comment] 2019-12-21 05:14
I just wanted to let you know so I tested the driver on both my laptop with a 1050 and my PC with 1080(water-cooled) and on both it helped a lot I ran the wrong thing in admin mode last time. Still not perfect but it's playable not as good as the link cable ofc but that does not work on the laptop even tho it can run VR. i just ran it at 75% res on the laptop and lower bitrate and steam in lower res too but games were playable this time. Not sure whats is diffrent in the driver and why it wants steam in admin mode but it helped.

**Comment by coroiu** [comment] 2019-12-21 08:59
@JackD83 I don't think we should release the fix as it is right now. I wouldn't really say that I am proud of how the code looks. And yes, the admin rights thing is sub-optimal. On the change-log for the update on OBS (where I "stole" the fix from: https://obsproject.com/forum/threads/obs-studio-24-0-3-gpu-priority-fix-testing.111669/) they say that they are investigating a way to enable this fix without admin access. Maybe we should wait for that?

@clementkirton I'm glad it helped! The issue seems to be that the game gets priority on the GPU, starving ALVR of needed processing power, making the video encoding drop frames. The fix priorities ALVR (and vrserver which ALVR runs in) on top, taking processing power back from the games. But to do that it it needs admin privileges.

**Comment by T3ER** [comment] 2019-12-21 17:58
The driver made no real difference on image doubling. The most difference in smoothness I got was from cpu upgrade, from pentium g4560 to ryzen 5 1600. Controllers and head tracking stutter way less, from controllers stuttering every few frames to stuttering every half second. 
There used to be gradually increasing latency but that was caused by cpu bottleneck when cpu usage was full. This also happened when gpu was maxed out by the game but cpu wasn't. (No man's sky) No it is gone completely.
Head tracking used to stutter similar to what was shown in videos posted here but it was only about 1/3 as bad and happened every few seconds. Now it's way smoother, can't even tell unless I look down in steamvr 's default grid, even then it happens every few seconds and it's way less noticeable. The image doubling was and is present with old cpu and new. It's constant and is more noticeable with faster movements.

**Comment by orangpelupa** [comment] 2019-12-25 08:37
I still got the exact same issue despite now im
1. on a fresh win 10 
2. Ryzen 2600, GTX 1660 SUPER

Here's 

- a recording from Quest headset (stutter easiest to be seen on nearing the end)
- a recording from ALVR debug (stutter before i moved the controllers, i cant see it in the video tho as it refuse to play in MPC-HC)
- a frame-by-frame recording from avidemux

https://send.firefox.com/download/c22c7dfb8cdaab16/#3udtYUbsoUljmOuqbjOO6A

I also tried the modded dll by @coroiu but it have no effect for me. I only need to replace the file in ALVR and restart SteamVR right?

Oculus Link works 100% fine, no stutter.  Didn't try any game tho, i was just moving my head on the link home screen and it have no stutter (its also more responsive than ALVR, probably because it use USB cable)

**Comment by orangpelupa** [comment] 2019-12-29 02:31
I don't know how, i've managed to eliminate NVENC stutter (on GF Experience) without using RTSS. Unfortunately ALVR stutter is still there

Here's a stream dump from ALVR
https://send.firefox.com/download/190aca36c2edbf84/#hUVr1Z-LY5NYW1pIlZhQmw

the stutter is easier to notice if you play that at 50% rate (i used MPC BE)

**Comment by SSSTREDDD** [comment] 2020-02-11 22:46
I have this problem as well. ALVR is amazing, but this issue just drives me crazy. I have tried everything to try and get rid of it to no avail :(

**Comment by SSSTREDDD** [comment] 2020-03-06 18:14
OK so i tested closer to my access point and the issue went away! I have a very good network setup and my ubiquity 5G AC access point is just one floor above where I play. I was getting solid 866mbps but had the issue. I tried upstairs _(literally right next to the access point)_ and the stuttering stopped. So to solve this? I am getting another access point for my VR room, same ubiquity ac lite. Arrives today and I am very excited.

**Comment by JackD83** [comment] 2020-03-29 08:40
I merged the fix from @coroiu in lack of an alternative solution. You have to manually load vrmonitor.exe as administrator to make use of it. Launching SteamVR does not work due to security restrictions.

**Closed by JackD83** 2020-03-29 08:40 UTC

**Comment by orangpelupa** [comment] 2020-05-16 02:42
if anyone still get this jerkyness, workaround:
on ALVR v10, disable foveated. The jerkyness will only appear on the first few minutes, then it will be smooth sailing.

**Comment by orangpelupa** [comment] 2021-03-23 04:59
in the latest ALVR this issue is gone! No need to tweak settings. but I'm not sure its due to ALVR or due to newer NVIDIA driver.
